{
  Type: Exception,
  Message: The Message,
  StackTrace: 
at Tests.TaskMethodThatThrowsGeneric()
at VerifyTests.InnerVerifier.ThrowsTask[T](Func`1 target)
}