{
  Type: Exception,
  Message: The Message,
  StackTrace: 
at Tests.TaskMethodThatThrowsGeneric()
at VerifyTests.InnerVerifier.<ThrowsTask>d__21`1.MoveNext()
}