{
  Type: Exception,
  Message: The Message,
  StackTrace: 
at Tests.ValueTaskMethodThatThrowsGeneric()
at VerifyTests.InnerVerifier.<ThrowsValueTask>d__19`1.MoveNext()
}